### ISSUE TITLE
repairing ships

### ISSUE THREAD

**Issue by malytomas** [gdg-garage/space-tycoon#25]
should we add command for repairing ships?

@curusarn wrote:
>TL;DR: Imho we should. No having repairs could make aggressive strategies too easy and too powerful. And if there are too many ships dying then trading becomes very hard.

> Imho it makes sense to either:

>    allow any ship to repair itself anywhere (this way the repairs would have to be kinda slow so that it's not very easy to repair all of your ships)
>    allow shipyard ships to repair other ships (this way the repairs could be super fast because they are constrained by number of shipyards player has)

> Extra notes:

> Dangers of no repairs
Imho could be hard to defend yourself effectively. E.g. someone can send ships to attack your mothership or cargo ships and gradually kill them because of lack of repair. It could be really hard to write a meaningful defense against these "wear down" strategies. If there are too many ships dying then trading becomes very hard.

> Issues with automatic passive regeneration
I was considering if automatic regeneration amount would work. It could be hard for us to tune the regeneration amount imho. Also making ships "wait" so that they repair in safety without setting any command on them is weird - it requires bots to remember that they have the ship waiting on purpose.

Should repairs be paid?

**Comment by curusarn** [comment]
Good question.

Free repairs would be easier for the players because they don't have to figure out if they should be using the money for something else. 

Paid repairs have a weird edge-case where if you repair your ship you have lowered your net worth. This feels weird to me.
This could be solved by making ships worth proportional to their HP. But I'm not sure if I like the idea that your net worth gets lower because your fleet took a bunch of hits in a fight.

One disadvantage of free repairs could be that people can attack others and then recover without any monetary cost. But I think that's wouldn't be an issue if we make sure that it's not easy to repair a lot of ships at once. Either by requiring a shipyard for repairs or by slower repair speed.

Ultimately, imho, there just has to be something that makes sure that people can't repair everything too quickly. The bottleneck/limitation can be:
- paid repairs
- slower repair speed
- shipyards repair one ship at a time
- ??? (something else)

I think we only need one bottleneck/limitation.
Currently, I like the idea of having repair as a command for shipyards which means that you can repair one at a time by each shipyard. And because of this limitation the repairs could be free and reasonably fast.

I do like the idea of making the shipyard-capable ships important for the overall gameplay. I imagine that it could create exciting situations and strategies - e.g. having more shipyards, moving your shipyards, destroying enemy shipyards, etc.

Sorry for the wall of text.

**Comment by malytomas** [comment]
Suggestion: add 'healer' ship class.

**Comment by malytomas** [comment]
Solution:
- Ships have small passive regeneration.
- Ships also have a command to quickly repair themselves at some price.

Reasoning:
- Cargo ships can depend on passive regen, which shifts focus of combat ships on other combat ships.

Other notes:
- Shipyards repairing other ships: more complex implementation, difficult planning (shipyards are usually slower, so the ships that want to get repaired have to cooperate, and to plan to not wait for it).
- It is undesirable to make attacking way too damaging as that could make the game end with a stalemate.
