### ISSUE TITLE
destroyed or decommissioned ships

### ISSUE THREAD

**Issue by malytomas** [gdg-garage/space-tycoon#27]
what should happen with destroyed or decommissioned ships?

change them into a wreck - an empty but valid object with no owner?

what to do with other ships commands referencing the destroyed/decommissioned ship?

what to do with any cargo that was present at the ship when it was destroyed or decommissioned?

**Comment by curusarn** [comment]
I would prefer avoiding having wrecks that bots have to differentiate from ships that are alive. 

I think it's okay when my ship stops because the target was destroyed. But it should not happen in the middle of the tick - i.e. all movements valid at the start of the tick should be evaluated even if the target dies during the tick. (Is this how the evaluation order works already in the DB?) At the end of the tick, the invalid commands should be cleared from the table so that bots can easily see that the ship has nothing to do.

Imho cargo on destroyed ships should be lost. Being able to steal cargo would be too much motivation for attacking others and it adds more complexity to the game.

**Comment by malytomas** [comment]
I am not sure I follow your first paragraph.

Currently, when a ship is destroyed, it is kept in the database as actual ship with zero life. Any assigned command is always removed. Its cargo is preserved and other ships (same player) can take it.
I do not like that bots have to check if their ship is alive or not, hence the question.

What I meant by wrecks is to have another type of objects (planets, ships, wrecks). Therefore bots would not have to differentiate their ships from wrecks.

In summary, I see these options:
- keep ship (with zero life) and its cargo (current behavior) - allows the original owner to recover the goods, but the bot has to differentiate between alive and dead ships.
- completely remove the ship - its cargo is permanently lost and affected commands have to be addressed.
- change the ship into a wreck, preserving ownership - cargo is preserved and can be recovered by the same player only. some commands become invalid, some are ok.
- change ship into a wreck, removing ownership - cargo may or may not be preserved, but it would be recoverable by anybody. some commands become invalid.

**Comment by malytomas** [comment]
As for the movement:
moving ships is the first thing to process and will therefore always happen even if some targeted ships are destroyed afterwards.

**Comment by curusarn** [comment]
> I am not sure I follow your first paragraph.
I didn't realize how it's currently implemented. I though that ships are currently not sent to players once destroyed so having the concept of wrecks at seemed like added complexity. Now I see that having separate wreck objects is "simpler" (for bots) than what we currently have.

> I do not like that bots have to check if their ship is alive or not, hence the question.
Yeah, agreed.

> completely remove the ship - its cargo is permanently lost and affected commands have to be addressed.
I think I prefer this one because it's very simple. No complexity for bots, no complexity in visualization, etc.

> change ship into a wreck, removing ownership - cargo may or may not be preserved, but it would be recoverable by anybody. some commands become invalid.
I fear that this will give people too much motivation for aggressive strategies. I think that damaging others is enough reason for aggression since destroying ships and cargo lowers net worth of players.

> change the ship into a wreck, preserving ownership - cargo is preserved and can be recovered by the same player only. some commands become invalid, some are ok.
This is also okay imho. But honestly I think I would prefer the players to spend their time writing attack/defense/trading logic instead of logic of when it is safe enough to go back and pick up cargo.

**Comment by malytomas** [comment]
Maybe original owners could recover wrecks with shipyards and restore them into new ships of the same class at reduced price?

**Comment by curusarn** [comment]
The more I think about this the more I like the simple solution - i.e. `completely remove the ship`.

If we find out that the game is too simple during testing we can add this feature later.

**Comment by curusarn** [comment]
The more I think about this the more I like the simple solution - i.e. `completely remove the ship`.

If we find out that the game is too simple during testing we can add this feature later.

**Comment by malytomas** [comment]
Suggestion: add ship class 'Rogue' that can steal cargo from other ships.

**Comment by malytomas** [comment]
Further idea: leave cargo with some probability.

**Comment by malytomas** [comment]
Accepted solution: ships are fully destroyed. Cargo is lost.

**Comment by malytomas** [comment]
removing the ship from the database is not possible as that would violate foreign keys in some other tables (eg. combat reports).

i will probably add wrecks, even if they will not be used for any game mechanics.
