### ISSUE TITLE
constructing ships taking multiple ticks

### ISSUE THREAD

**Issue by malytomas** [gdg-garage/space-tycoon#29]
what do you think about ships construction taking several ticks?

possible idea is that the ship is actually created the first tick, but with only half its maximum life, and then the construction continues by repairing the ship to full life.

**Comment by curusarn** [comment]
The only risk I can see without this limitation is that someone can build an enormous number of ships very quickly.
Which could lead to strong sneaky attacks. I'm not sure if we mind people buying a lot of ships at once.

I'm inclined to think that having money and having a shipyard at the right location which seems like sufficient limitation. 


But if we wanted ship construction to take multiple turns I would make the command take multiple turns and then spawn the ship at the end. I don't think we want to break "construct" into "construct+repair" because then the bots can cancel the repair leaving the ship with less than full HP. From the player perspective it would look like the ship was built with half HP.
Explaining to players that they need to wait for the repairs after they construct a ship is something I would rather avoid.

**Comment by malytomas** [comment]
> I don't think we want to break "construct" into "construct+repair" because then the bots can cancel the repair leaving the ship with less than full HP.

I meant that as a feature :D giving the bots a choice to use the ship earlier but with greater risk.

**Comment by curusarn** [comment]
Oh I see :D

I think it's too complex. I think people are going to have enough fun/work with ale the other features of the game.

**Comment by curusarn** [comment]
Bots can still "experience the greater risk" when the ship gets damaged later by enemies. :D

**Comment by tivvit** [comment]
IMHO for now it is enough to spawn ships instantly

**Comment by tivvit** [comment]
I maybe have a perfect argument against this. It also applies for repairs. 

From my perception the game is too slow /short. In 2h epoch -7200 ticks you can travel between 2 planets which are 10 tics apart 360* (roundtrip and distance). The distances are going to be much bigger imho, therefore there are only a few things to do in an epoch.  There is no reason to make the commands slower. Of course I may be wrong - this has to be tested.

**Comment by malytomas** [comment]
Rejected
