### ISSUE TITLE
random map generation with some progression during epochs

### ISSUE THREAD

**Issue by tivvit** [gdg-garage/space-tycoon#31]
Just an idea we discussed with @curusarn in person. 

Maybe we can change the parameters for map generation during the epochs to force the bots to be more clever. The number of planets and their distribution (clusters) comes to mind.

Something like - lowering the number of planets for each epoch to make the game more aggressive.

**Comment by malytomas** [comment]
> lowering the number of planets for each epoch

this might require changing some parameters in the bots, which most will do manually rather then figuring out some equations. i think such periodical manual intervenes should be unnecessary.

otherwise, i agree that the map should be generated semi-randomly to ensure that plays do not repeat over epochs.

current algorithm generates 200..300 stars and 1..6 planets at each star. the median for planets is at 2.25 planets per star.
(it does not generate actual stars - they are just the coordinates of the center for a bunch of planets)

**Comment by malytomas** [comment]
Rejected
